
name: Deploy Weather Bot

on:
  push:
    branches:
      - main  # Срабатывает при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/debian/weather_bot
            git pull origin main
            ./venv/bin/pip install -r requirements.txt
            sudo systemctl restart weather_bot

#